/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.sql.Connection;

import javax.swing.JOptionPane;
import Conexion.BDConexion;


/**
 *
 * @author tridente
 */
public class InterfazCliente extends javax.swing.JFrame {

    
    /**
     * Creates new form InterfazCliente
     */
    public InterfazCliente() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnEdi = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnReg = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtFil = new javax.swing.JTextField();
        btnFil = new javax.swing.JButton();
        txtRut = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        txtp = new javax.swing.JTextField();
        txtreg = new javax.swing.JTextField();
        txtcom = new javax.swing.JTextField();
        txtm = new javax.swing.JTextField();
        txtciu = new javax.swing.JTextField();
        txtdir = new javax.swing.JTextField();
        txtcor = new javax.swing.JTextField();
        txttel = new javax.swing.JTextField();
        TxtRut = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel233 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnEdi.setText("Editar");
        getContentPane().add(BtnEdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, -1, -1));

        jLabel8.setText("Apellido Materno");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 208, -1, -1));

        jLabel9.setText("Rut ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 113, -1, -1));

        jLabel11.setText("Nombre");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 139, -1, -1));

        jLabel12.setText("Apellido Paterno");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 177, -1, -1));

        btnReg.setText("Registrar");
        btnReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegActionPerformed(evt);
            }
        });
        getContentPane().add(btnReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        jLabel44.setText("Id Cliente");
        getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 78, -1, -1));

        jLabel3.setText("Direccón");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 346, -1, -1));

        jLabel13.setText("Correo");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 377, -1, -1));

        jLabel23.setText("Telefono");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 408, -1, -1));

        jButton9.setText("Agregar otro telefono");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 436, -1, -1));

        jLabel24.setText("Comuna");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 239, -1, -1));

        jLabel36.setText("Región");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 277, -1, -1));

        jLabel37.setText("Ciudad");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 308, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Cliente", "Rut", "Apellido P", "Apellido M", "Comuna", "Region", "Ciudad", "Direccion", "Correo", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 616, 331));
        getContentPane().add(txtFil, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 90, 89, -1));

        btnFil.setText("Filtrar");
        getContentPane().add(btnFil, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 90, -1, -1));

        txtRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutActionPerformed(evt);
            }
        });
        txtRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRutKeyTyped(evt);
            }
        });
        getContentPane().add(txtRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 110, 93, -1));

        txtnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomActionPerformed(evt);
            }
        });
        txtnom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnomKeyTyped(evt);
            }
        });
        getContentPane().add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 136, 93, -1));

        txtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpActionPerformed(evt);
            }
        });
        txtp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpKeyTyped(evt);
            }
        });
        getContentPane().add(txtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 174, 93, -1));

        txtreg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtregKeyTyped(evt);
            }
        });
        getContentPane().add(txtreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 274, 93, -1));

        txtcom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcomKeyTyped(evt);
            }
        });
        getContentPane().add(txtcom, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 241, 93, -1));

        txtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmActionPerformed(evt);
            }
        });
        txtm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmKeyTyped(evt);
            }
        });
        getContentPane().add(txtm, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 93, -1));

        txtciu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtciuActionPerformed(evt);
            }
        });
        txtciu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtciuKeyTyped(evt);
            }
        });
        getContentPane().add(txtciu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 305, 93, -1));

        txtdir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdirKeyTyped(evt);
            }
        });
        getContentPane().add(txtdir, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 343, 93, -1));
        getContentPane().add(txtcor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 374, 93, -1));

        txttel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelKeyTyped(evt);
            }
        });
        getContentPane().add(txttel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 405, 93, -1));

        TxtRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRutActionPerformed(evt);
            }
        });
        TxtRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtRutKeyTyped(evt);
            }
        });
        getContentPane().add(TxtRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 23, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Cliente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 11, -1, -1));

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 78, -1, -1));

        jLabel233.setText("-");
        getContentPane().add(jLabel233, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 113, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/folder/logoExtraLimpioFinal.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, -1, 90));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/folder/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegActionPerformed
        Connection conn = BDConexion.getConexion();
        if (conn != null){
            if(!validaDatosServ()){
                JOptionPane.showMessageDialog(this,"Ingrese sus datos, por favor.","No hay datos",3);
            }
        }
    }//GEN-LAST:event_btnRegActionPerformed

    
    private void txtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpActionPerformed

    private void txtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmActionPerformed

    private void txtciuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtciuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtciuActionPerformed

    private void txtRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutActionPerformed

    
    
    private void TxtRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRutActionPerformed

    private void txtnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void txtRutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutKeyTyped
        // TODO add your handling code here:
        char c; 
        c = evt.getKeyChar ();
        if((c<'0' || c>'9')) evt.consume();
        
    }//GEN-LAST:event_txtRutKeyTyped

    private void TxtRutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtRutKeyTyped
        // TODO add your handling code here:
        char c; 
        c = evt.getKeyChar ();
        if((c<'0' || c>'9')) evt.consume();
    }//GEN-LAST:event_TxtRutKeyTyped

    private void txtnomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomKeyTyped
        // TODO add your handling code here:
        char c; 
        c = evt.getKeyChar ();
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' '||c>' ')) evt.consume();
    }//GEN-LAST:event_txtnomKeyTyped

    private void txtpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpKeyTyped
        // TODO add your handling code here:
        char c; 
        c = evt.getKeyChar ();
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' '||c>' ')) evt.consume();
    }//GEN-LAST:event_txtpKeyTyped

    private void txtmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmKeyTyped
        // TODO add your handling code here:
        char c; 
        c = evt.getKeyChar ();
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' '||c>' ')) evt.consume();
    }//GEN-LAST:event_txtmKeyTyped

    private void txtcomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcomKeyTyped
        // TODO add your handling code here:
        char c; 
        c = evt.getKeyChar ();
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' '||c>' ')) evt.consume();
    }//GEN-LAST:event_txtcomKeyTyped

    private void txtregKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtregKeyTyped
        // TODO add your handling code here:
        char c; 
        c = evt.getKeyChar ();
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' '||c>' ')) evt.consume();
    }//GEN-LAST:event_txtregKeyTyped

    private void txtciuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtciuKeyTyped
        // TODO add your handling code here:
        char c; 
        c = evt.getKeyChar ();
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' '||c>' ')) evt.consume();
    }//GEN-LAST:event_txtciuKeyTyped

    private void txttelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelKeyTyped
        // TODO add your handling code here:
        char c; 
        c = evt.getKeyChar ();
        if((c<'0' || c>'9')) evt.consume();
    }//GEN-LAST:event_txttelKeyTyped

    private void txtdirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdirKeyTyped
        // TODO add your handling code here:
      
               
               
          
    }//GEN-LAST:event_txtdirKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEdi;
    private javax.swing.JTextField TxtRut;
    private javax.swing.JButton btnFil;
    private javax.swing.JButton btnReg;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel233;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtFil;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtciu;
    private javax.swing.JTextField txtcom;
    private javax.swing.JTextField txtcor;
    private javax.swing.JTextField txtdir;
    private javax.swing.JTextField txtm;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtp;
    private javax.swing.JTextField txtreg;
    private javax.swing.JTextField txttel;
    // End of variables declaration//GEN-END:variables

    private boolean validaDatosServ() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
