/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author tridente
 */
public class InterfazInicio extends javax.swing.JFrame {

    /**
     * Creates new form InterfazInicio
     */
    public InterfazInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        MenuSuc = new javax.swing.JMenuItem();
        MenuVen = new javax.swing.JMenuItem();
        MenuCli = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MenuIns = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        MenuSer = new javax.swing.JMenuItem();
        MenuRec = new javax.swing.JMenu();
        MenuRecepciones = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        MenuOr = new javax.swing.JMenuItem();
        MenuSalir = new javax.swing.JMenu();
        salir = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ExtraLimpio");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/folder/logoExtraLimpio.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 410, 290));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/folder/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 400));

        jMenu7.setText("Sucursales");
        jMenu7.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jMenu7ItemStateChanged(evt);
            }
        });
        jMenu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu7ActionPerformed(evt);
            }
        });

        MenuSuc.setText("Añadir Sucursal");
        MenuSuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSucActionPerformed(evt);
            }
        });
        jMenu7.add(MenuSuc);

        MenuVen.setText("Añadir Vendedor");
        MenuVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuVenActionPerformed(evt);
            }
        });
        jMenu7.add(MenuVen);

        MenuCli.setText("Añadir Cliente");
        MenuCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCliActionPerformed(evt);
            }
        });
        jMenu7.add(MenuCli);

        jMenuBar1.add(jMenu7);

        jMenu3.setText("Insumos");

        MenuIns.setText("Añadir Insumos");
        MenuIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuInsActionPerformed(evt);
            }
        });
        jMenu3.add(MenuIns);

        jMenuBar1.add(jMenu3);

        jMenu8.setText("Servicios");

        MenuSer.setText("Añadir Servicio");
        MenuSer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSerActionPerformed(evt);
            }
        });
        jMenu8.add(MenuSer);

        jMenuBar1.add(jMenu8);

        MenuRec.setText("Recepciones");

        MenuRecepciones.setText("Recepcion");
        MenuRecepciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRecepcionesActionPerformed(evt);
            }
        });
        MenuRec.add(MenuRecepciones);

        jMenuBar1.add(MenuRec);

        jMenu1.setText("Generar");

        MenuOr.setText("Orden");
        MenuOr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuOrActionPerformed(evt);
            }
        });
        jMenu1.add(MenuOr);

        jMenuBar1.add(jMenu1);

        MenuSalir.setText("Salir");
        MenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSalirActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        MenuSalir.add(salir);

        Salir.setText("Cerrar session");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        MenuSalir.add(Salir);

        jMenuBar1.add(MenuSalir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuSucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSucActionPerformed
        // TODO add your handling code here:
      
        //aqui se crea la variable que redirige a las pestañas indicadas
        InterfazSucursal sucursal = new InterfazSucursal();
        sucursal.setVisible(true);
    }//GEN-LAST:event_MenuSucActionPerformed

    private void MenuVenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuVenActionPerformed
        // TODO add your handling code here:
        
        
          //aqui se crea la variable que redirige a las pestañas indicadas
        InterfazVendedor vendedores = new InterfazVendedor();
        vendedores.setVisible(true);
    }//GEN-LAST:event_MenuVenActionPerformed

    private void MenuCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCliActionPerformed
        // TODO add your handling code here:
        
          //aqui se crea la variable que redirige a las pestañas indicadas
          InterfazCliente clientes = new InterfazCliente();
          clientes.setVisible(true);
    }//GEN-LAST:event_MenuCliActionPerformed

    private void MenuInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuInsActionPerformed
        // TODO add your handling code here:
        
          //aqui se crea la variable que redirige a las pestañas indicadas
        InterfazInsumo insumo = new InterfazInsumo();
        insumo.setVisible(true);
    }//GEN-LAST:event_MenuInsActionPerformed

    private void MenuSerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSerActionPerformed
        // TODO add your handling code here:
        
          //aqui se crea la variable que redirige a las pestañas indicadas
          InterfazServicio servicio = new InterfazServicio();
          servicio.setVisible(true);
    }//GEN-LAST:event_MenuSerActionPerformed

    private void MenuRecepcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRecepcionesActionPerformed
        // TODO add your handling code here:
        
          //aqui se crea la variable que redirige a las pestañas indicadas
          InterfazRecepcion recepcion = new InterfazRecepcion();
          recepcion.setVisible(true);
    }//GEN-LAST:event_MenuRecepcionesActionPerformed

    private void MenuOrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuOrActionPerformed
        // TODO add your handling code here:
        
          //aqui se crea la variable que redirige a las pestañas indicadas
          InterfazOrden orden = new InterfazOrden();
          orden.setVisible(true);
    }//GEN-LAST:event_MenuOrActionPerformed

    private void MenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSalirActionPerformed
        // TODO add your handling code here:
     
        
    }//GEN-LAST:event_MenuSalirActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
         
        //metodo para decir que en esta pantalla la cierre y los diriga al inicio de sesion
           this.setVisible(false); 
new LavanderiaInterfaz().setVisible(true); 
    }//GEN-LAST:event_SalirActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void jMenu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu7ActionPerformed

    private void jMenu7ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jMenu7ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu7ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuCli;
    private javax.swing.JMenuItem MenuIns;
    private javax.swing.JMenuItem MenuOr;
    private javax.swing.JMenu MenuRec;
    private javax.swing.JMenuItem MenuRecepciones;
    private javax.swing.JMenu MenuSalir;
    private javax.swing.JMenuItem MenuSer;
    private javax.swing.JMenuItem MenuSuc;
    private javax.swing.JMenuItem MenuVen;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenuItem salir;
    // End of variables declaration//GEN-END:variables
}
