/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Conexion.BDConexion;
import Clases.*;
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Andres
 * @version 2
 */
public final class InterfazSucursal extends javax.swing.JFrame {
 
    /**
     * Creates new form InterfazSucursal
     */
    public InterfazSucursal() {
        
        //esconder los campos
        
        initComponents();
        Region cc = new Region();
        
        DefaultComboBoxModel modelEstado = new DefaultComboBoxModel(cc.mostrarRegion());
        
        //Combobox Region
        cbxRegion.setModel(modelEstado);
        //Tabla Sucursal
        TBSucursal.getTableHeader().setReorderingAllowed(false);
        BDSucursal.listar(TBSucursal);
//        comprobarCampos();
        panelCampos.setVisible(false);
        panelInferiorBotones.setVisible(false);    
    }
    
 public boolean isEmail(String correo){
        
        Pattern pat = null;
        Matcher mat = null;
        pat = Pattern.compile("^[\\w\\-\\+]+(\\.[\\w\\-\\_]+)*@([A-Za-z0-9-]+\\.)+[A-Za-z]{2,4}$");
        mat = pat.matcher(correo);
        if(mat.find()){
            return true;
            
        }else{
            return false;
        }
    }
    
    
    public void obtenerCampos(){
        int rowSel = TBSucursal.getSelectedRow();
        txtID.setText(String.valueOf(TBSucursal.getValueAt(rowSel, 0)));
        txtNomSuc.setText(String.valueOf(TBSucursal.getValueAt(rowSel, 1)));
        txtTel1.setText(String.valueOf(TBSucursal.getValueAt(rowSel, 5)));
        txtTel2.setText(String.valueOf(TBSucursal.getValueAt(rowSel, 6)));
        txtDir.setText(String.valueOf(TBSucursal.getValueAt(rowSel, 7)));
        txtCor.setText(String.valueOf(TBSucursal.getValueAt(rowSel, 8)));
            Region reg = new Region();
            
            Ciudad mun = new Ciudad();
            Comuna loc = new Comuna();
            cbxRegion.setSelectedIndex(reg.mostrarRegionV2(String.valueOf(TBSucursal.getValueAt(rowSel, 4))));
            cbxCiudad.setSelectedIndex(mun.mostrarCiudadV2(cbxRegion.getSelectedItem().toString()));
            cbxComuna.setSelectedItem(loc.mostrarComunaV2(cbxCiudad.getSelectedItem().toString()));
            
            
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContenedor = new javax.swing.JPanel();
        panelCampos = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTel2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDir = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTel1 = new javax.swing.JTextField();
        txtID = new javax.swing.JLabel();
        cbxRegion = new javax.swing.JComboBox<>();
        cbxCiudad = new javax.swing.JComboBox<>();
        cbxComuna = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNomSuc = new javax.swing.JTextField();
        panelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBSucursal = new javax.swing.JTable();
        panelSuperiorBotones = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        panelInferiorBotones = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        panelFiltrar = new javax.swing.JPanel();
        jComboBoxItemBusqueda = new javax.swing.JComboBox<>();
        txtBusqueda = new javax.swing.JTextField();
        btnFiltrar = new javax.swing.JButton();
        btnQuitarFiltro = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        PanelContenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCampos.setForeground(new java.awt.Color(187, 187, 100));
        panelCampos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("ID");
        panelCampos.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 30, -1, 20));

        jLabel1.setText("Region");
        panelCampos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 50, 20));

        jLabel2.setText("Telefono 2");
        panelCampos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 70, 20));

        txtTel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTel2ActionPerformed(evt);
            }
        });
        txtTel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTel2KeyTyped(evt);
            }
        });
        panelCampos.add(txtTel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 180, -1));

        jLabel3.setText("Direccion");
        panelCampos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 60, 20));

        txtDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirActionPerformed(evt);
            }
        });
        panelCampos.add(txtDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 180, -1));

        jLabel4.setText("Correo");
        panelCampos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 50, 20));

        txtCor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorFocusLost(evt);
            }
        });
        txtCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorActionPerformed(evt);
            }
        });
        txtCor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorKeyTyped(evt);
            }
        });
        panelCampos.add(txtCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 180, -1));

        jLabel7.setText("Telefono");
        panelCampos.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 60, 20));

        txtTel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTel1ActionPerformed(evt);
            }
        });
        txtTel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTel1KeyTyped(evt);
            }
        });
        panelCampos.add(txtTel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 180, -1));
        panelCampos.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 30, 50, 20));

        cbxRegion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxRegion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxRegionItemStateChanged(evt);
            }
        });
        cbxRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxRegionActionPerformed(evt);
            }
        });
        panelCampos.add(cbxRegion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 180, -1));

        cbxCiudad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxCiudad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCiudadItemStateChanged(evt);
            }
        });
        panelCampos.add(cbxCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 180, -1));

        cbxComuna.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxComuna.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxComunaItemStateChanged(evt);
            }
        });
        cbxComuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxComunaActionPerformed(evt);
            }
        });
        panelCampos.add(cbxComuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 180, -1));

        jLabel8.setText("Comuna");
        panelCampos.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 50, 20));

        jLabel9.setText("Ciudad");
        panelCampos.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 50, 20));

        jLabel14.setText("Nombre");
        panelCampos.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        txtNomSuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomSucActionPerformed(evt);
            }
        });
        txtNomSuc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomSucKeyTyped(evt);
            }
        });
        panelCampos.add(txtNomSuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 180, -1));

        PanelContenedor.add(panelCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 320, 400));

        panelTabla.setLayout(new java.awt.BorderLayout());

        TBSucursal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title6"
            }
        ));
        TBSucursal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBSucursalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBSucursal);

        panelTabla.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        PanelContenedor.add(panelTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 670, 180));

        panelSuperiorBotones.setMaximumSize(new java.awt.Dimension(780, 45));
        panelSuperiorBotones.setMinimumSize(new java.awt.Dimension(780, 45));
        panelSuperiorBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setText("Agregar");
        btnAgregar.setMaximumSize(new java.awt.Dimension(200, 23));
        btnAgregar.setMinimumSize(new java.awt.Dimension(200, 23));
        btnAgregar.setPreferredSize(new java.awt.Dimension(200, 23));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        panelSuperiorBotones.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 5, -1, -1));

        btnModificar.setText("Modificar");
        btnModificar.setMaximumSize(new java.awt.Dimension(200, 23));
        btnModificar.setMinimumSize(new java.awt.Dimension(200, 23));
        btnModificar.setPreferredSize(new java.awt.Dimension(200, 23));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        panelSuperiorBotones.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 5, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.setMaximumSize(new java.awt.Dimension(200, 23));
        btnEliminar.setMinimumSize(new java.awt.Dimension(200, 23));
        btnEliminar.setPreferredSize(new java.awt.Dimension(200, 23));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        panelSuperiorBotones.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 5, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/folder/Fondo.jpg"))); // NOI18N
        panelSuperiorBotones.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 30));

        PanelContenedor.add(panelSuperiorBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 670, -1));

        panelInferiorBotones.setMaximumSize(new java.awt.Dimension(780, 45));
        panelInferiorBotones.setMinimumSize(new java.awt.Dimension(780, 45));
        panelInferiorBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardar.setText("Guardar");
        btnGuardar.setMaximumSize(new java.awt.Dimension(200, 23));
        btnGuardar.setMinimumSize(new java.awt.Dimension(200, 23));
        btnGuardar.setPreferredSize(new java.awt.Dimension(200, 23));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panelInferiorBotones.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.setMaximumSize(new java.awt.Dimension(200, 23));
        btnLimpiar.setMinimumSize(new java.awt.Dimension(200, 23));
        btnLimpiar.setPreferredSize(new java.awt.Dimension(200, 23));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        panelInferiorBotones.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        PanelContenedor.add(panelInferiorBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 240, 80));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("SUCURSAL");
        lblTitulo.setMaximumSize(new java.awt.Dimension(780, 44));
        lblTitulo.setMinimumSize(new java.awt.Dimension(780, 44));
        lblTitulo.setPreferredSize(new java.awt.Dimension(780, 44));
        PanelContenedor.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 940, 60));

        panelFiltrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxItemBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "id_sucursal" }));
        jComboBoxItemBusqueda.setMaximumSize(new java.awt.Dimension(200, 23));
        jComboBoxItemBusqueda.setMinimumSize(new java.awt.Dimension(200, 23));
        jComboBoxItemBusqueda.setPreferredSize(new java.awt.Dimension(200, 23));
        jComboBoxItemBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxItemBusquedaActionPerformed(evt);
            }
        });
        panelFiltrar.add(jComboBoxItemBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 5, -1, -1));

        txtBusqueda.setMaximumSize(new java.awt.Dimension(200, 23));
        txtBusqueda.setMinimumSize(new java.awt.Dimension(200, 23));
        txtBusqueda.setPreferredSize(new java.awt.Dimension(200, 23));
        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyTyped(evt);
            }
        });
        panelFiltrar.add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 5, -1, -1));

        btnFiltrar.setText("Filtrar");
        btnFiltrar.setMaximumSize(new java.awt.Dimension(100, 23));
        btnFiltrar.setMinimumSize(new java.awt.Dimension(100, 23));
        btnFiltrar.setPreferredSize(new java.awt.Dimension(100, 23));
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });
        panelFiltrar.add(btnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 5, -1, -1));

        btnQuitarFiltro.setText("Quitar filtro");
        btnQuitarFiltro.setMaximumSize(new java.awt.Dimension(100, 23));
        btnQuitarFiltro.setMinimumSize(new java.awt.Dimension(100, 23));
        btnQuitarFiltro.setPreferredSize(new java.awt.Dimension(100, 23));
        btnQuitarFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarFiltroActionPerformed(evt);
            }
        });
        panelFiltrar.add(btnQuitarFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 5, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/folder/Fondo.jpg"))); // NOI18N
        panelFiltrar.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 30));

        PanelContenedor.add(panelFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 100, 670, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/folder/Fondo.jpg"))); // NOI18N
        PanelContenedor.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 1020));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 1025, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTel2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTel2ActionPerformed

    private void txtTel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTel1ActionPerformed

    private void TBSucursalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBSucursalMouseClicked
        //Al seleccionar item de la tabla, se actualizan campos y se activa botón Modificar
        if(btnAgregar.isSelected()){
            btnAgregar.setSelected(false);
            btnAgregar.setBackground(null);
            btnModificar.setSelected(true);
            btnModificar.setBackground(Color.GRAY);
        }
//        comprobarCampos();
        obtenerCampos();
    }//GEN-LAST:event_TBSucursalMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Limpiar.contenidoPanel(panelCampos);
        btnAgregar.setSelected(true);
        btnAgregar.setBackground(Color.GRAY);
        btnModificar.setSelected(false);
        btnModificar.setBackground(null);
     
        Connection conn;
        Statement st;
        ResultSet rs;
        
            
        try {
            conn = BDConexion.getConexion();
            st = conn.createStatement();
            rs = st.executeQuery("SELECT * FROM sucursal ORDER by id_sucursal desc LIMIT 1");
            while(rs.next()){
                
                int p=Integer.parseInt(rs.getString("id_sucursal"))+1;
                txtID.setText(Integer.toString(p));
                txtID.disable();
            }
        } catch (Exception e) {
        }
       
        
        panelCampos.setVisible(true);
        panelInferiorBotones.setVisible(true);
        txtTel1.requestFocus();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        //Se activa selección de botón Modificar y de desactiva botón Agregar
        btnModificar.setSelected(true);
        btnModificar.setBackground(Color.GRAY);
        btnAgregar.setSelected(false);
        btnAgregar.setBackground(null);

        //Se obtienen datos de fila seleccionada en la tabla y se cargan los campos correspondientes
        obtenerCampos();

//        comprobarCampos();
        panelCampos.setVisible(true);
        panelInferiorBotones.setVisible(true);
        txtTel1.requestFocus();

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       //este boton manda un mensaje de alerta que dira si realmente se desea eliminar 
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Esta seguro?", "Alerta!", JOptionPane.YES_NO_OPTION);
        if ( respuesta == 0){
            //Se obtiene ID para eliminar registro
            int rowSel = TBSucursal.getSelectedRow();
            int reg = (Integer) TBSucursal.getValueAt(rowSel, 0);
            BDSucursal.eliminar(reg);
            BDSucursal.listar(TBSucursal);
            Limpiar.contenidoPanel(panelCampos);
            txtID.setText("");
        }
//        comprobarCampos();
    }//GEN-LAST:event_btnEliminarActionPerformed
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        //Se agrega o modifica registro según botón seleccionado.
        try{
            
            String id = txtID.getText();
            String nom= txtNomSuc.getText();
            String tel1 = txtTel1.getText();
            String tel2 = txtTel2.getText();
            String dir = txtDir.getText();
            String cor = txtCor.getText();
            Comuna loc = (Comuna) cbxComuna.getSelectedItem();
            String com2=Integer.toString(loc.getId());
            
            if(btnAgregar.isSelected()){
                
                BDSucursal.insertar(id,nom,com2, tel1, tel2,dir,cor);
                BDSucursal.listar(TBSucursal);
                Limpiar.contenidoPanel(panelCampos);
//                comprobarCampos();
            }else if(btnModificar.isSelected()){
                int idf = Integer.parseInt(id);
                BDSucursal.modificar(idf,nom, com2, tel1, tel2,dir,cor);
                BDSucursal.listar(TBSucursal);
                Limpiar.contenidoPanel(panelCampos);
//                comprobarCampos();
            }
        }catch(Exception e){
            System.err.println("Excepción al guardar : " + e);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        //Se limpias campos
        Limpiar.contenidoPanel(panelCampos);
//        comprobarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jComboBoxItemBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxItemBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxItemBusquedaActionPerformed

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
        btnFiltrar.requestFocus();
    }//GEN-LAST:event_txtBusquedaActionPerformed

    private void txtBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();        
    }//GEN-LAST:event_txtBusquedaKeyTyped
 
    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        String criterioBusqueda = jComboBoxItemBusqueda.getSelectedItem().toString();
        String textoBusqueda = txtBusqueda.getText();
        System.out.println("Campo a buscar: " + criterioBusqueda);
        System.out.println("Criterio a buscar: " + criterioBusqueda);

        if (criterioBusqueda.equals("id_sucursal")){
            BDSucursal.filtrar(TBSucursal, "id_sucursal", textoBusqueda);
        }else if (criterioBusqueda.equals("Nombre")){
            BDSucursal.filtrar(TBSucursal, "direccion", textoBusqueda);
        }
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void btnQuitarFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarFiltroActionPerformed
        txtBusqueda.setText("");
        BDSucursal.listar(TBSucursal);
//        comprobarCampos();
    }//GEN-LAST:event_btnQuitarFiltroActionPerformed

    private void txtTel1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTel1KeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
        if (txtTel1.getText().length()>=9) {
            evt.consume();
            
        }
    }//GEN-LAST:event_txtTel1KeyTyped

    private void txtTel2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTel2KeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
        if (txtTel2.getText().length()>=9) {
            evt.consume();
            
        }
    }//GEN-LAST:event_txtTel2KeyTyped

    private void txtCorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorFocusLost
      if(isEmail(txtCor.getText())){

        }else{
            JOptionPane.showMessageDialog(null, "Email incorrecto", "Validar email"
                ,JOptionPane.INFORMATION_MESSAGE);
            txtCor.requestFocus();
        }
    }//GEN-LAST:event_txtCorFocusLost

    private void txtDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirActionPerformed

    private void txtCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorActionPerformed

    private void cbxRegionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxRegionItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            Region est = (Region) cbxRegion.getSelectedItem();
            Ciudad mun = new Ciudad();
            DefaultComboBoxModel modelMunicipio = new DefaultComboBoxModel(mun.mostrarCiudad(est.getId()));
            cbxCiudad.setModel(modelMunicipio);
            cbxComuna.removeAllItems();
           
        }
    }//GEN-LAST:event_cbxRegionItemStateChanged

    private void cbxCiudadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCiudadItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            Ciudad mun = (Ciudad) cbxCiudad.getSelectedItem();
            Comuna loc = new Comuna();
            DefaultComboBoxModel modelLocalidad = new DefaultComboBoxModel(loc.mostrarComuna(mun.getId()));
            modelLocalidad.removeElementAt(0);
            cbxComuna.setModel(modelLocalidad);
        }
    }//GEN-LAST:event_cbxCiudadItemStateChanged

    private void cbxComunaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxComunaItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            Region est = (Region) cbxRegion.getSelectedItem();
            Ciudad mun = (Ciudad) cbxCiudad.getSelectedItem();
            Comuna loc = (Comuna) cbxComuna.getSelectedItem();

            

        }
    }//GEN-LAST:event_cbxComunaItemStateChanged

    private void cbxComunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxComunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxComunaActionPerformed

    private void cbxRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRegionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxRegionActionPerformed

    private void txtCorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorKeyTyped

    private void txtNomSucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomSucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomSucActionPerformed

    private void txtNomSucKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomSucKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomSucKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazSucursal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContenedor;
    private javax.swing.JTable TBSucursal;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnQuitarFiltro;
    private javax.swing.JComboBox<String> cbxCiudad;
    private javax.swing.JComboBox<String> cbxComuna;
    private javax.swing.JComboBox<String> cbxRegion;
    private javax.swing.JComboBox<String> jComboBoxItemBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelCampos;
    private javax.swing.JPanel panelFiltrar;
    private javax.swing.JPanel panelInferiorBotones;
    private javax.swing.JPanel panelSuperiorBotones;
    private javax.swing.JPanel panelTabla;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtDir;
    private javax.swing.JLabel txtID;
    private javax.swing.JTextField txtNomSuc;
    private javax.swing.JTextField txtTel1;
    private javax.swing.JTextField txtTel2;
    // End of variables declaration//GEN-END:variables

    private boolean validaDatosServ() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
}
