/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Conexion.BDConexion;
import Clases.*;
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Andres
 * @version 2
 */
public final class InterfazVendedor extends javax.swing.JFrame {
 
    /**
     * Creates new form InterfazVendedor
     */
    public InterfazVendedor() {
        
        //esconder los campos
        
        initComponents();
        Region cc = new Region();
        Sucursal s= new Sucursal();
        DefaultComboBoxModel modelEstado = new DefaultComboBoxModel(cc.mostrarRegion());
        DefaultComboBoxModel modelSucursal = new DefaultComboBoxModel(s.mostrarSucursal());
        //Combobox Region
        cbxRegion.setModel(modelEstado);
        //Combobox Sucursal
        cbxSucursal.setModel(modelSucursal);
        //Tabla Sucursal
        TBVendedor.getTableHeader().setReorderingAllowed(false);
        BDVendedor.listar(TBVendedor);
//        comprobarCampos();
        panelCampos.setVisible(false);
        panelInferiorBotones.setVisible(false);    
    }
    
    
    public void obtenerCampos(){
        int rowSel = TBVendedor.getSelectedRow();
        txtID.setText(String.valueOf(TBVendedor.getValueAt(rowSel, 0)));
        
        txtRut.setText(String.valueOf(TBVendedor.getValueAt(rowSel, 1)).substring(0,8));
        txtRut2.setText(String.valueOf(TBVendedor.getValueAt(rowSel, 1)).substring(9));
        txtNombre.setText(String.valueOf(TBVendedor.getValueAt(rowSel, 2)));
        txtPaterno.setText(String.valueOf(TBVendedor.getValueAt(rowSel, 3)));
        txtMaterno.setText(String.valueOf(TBVendedor.getValueAt(rowSel, 4)));
        txtDir.setText(String.valueOf(TBVendedor.getValueAt(rowSel, 5)));
        txtTel.setText(String.valueOf(TBVendedor.getValueAt(rowSel, 6)));
        
            Region reg = new Region();
            Sucursal s = new Sucursal();
            Ciudad mun = new Ciudad();
            Comuna loc = new Comuna();
            cbxSucursal.setSelectedIndex(s.mostrarsucursalV2(String.valueOf(TBVendedor.getValueAt(rowSel, 10))));
            cbxRegion.setSelectedIndex(reg.mostrarRegionV2(String.valueOf(TBVendedor.getValueAt(rowSel, 9))));
            cbxCiudad.setSelectedIndex(mun.mostrarCiudadV2(cbxRegion.getSelectedItem().toString()));
            cbxComuna.setSelectedItem(loc.mostrarComunaV2(cbxCiudad.getSelectedItem().toString()));
            
            
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContenedor = new javax.swing.JPanel();
        panelCampos = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPaterno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMaterno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtRut2 = new javax.swing.JTextField();
        txtID = new javax.swing.JLabel();
        cbxRegion = new javax.swing.JComboBox<>();
        cbxCiudad = new javax.swing.JComboBox<>();
        cbxSucursal = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        txtDir = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbxComuna = new javax.swing.JComboBox<>();
        txtRut = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        panelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBVendedor = new javax.swing.JTable();
        panelSuperiorBotones = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        panelInferiorBotones = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        panelFiltrar = new javax.swing.JPanel();
        jComboBoxItemBusqueda = new javax.swing.JComboBox<>();
        txtBusqueda = new javax.swing.JTextField();
        btnFiltrar = new javax.swing.JButton();
        btnQuitarFiltro = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        PanelContenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCampos.setForeground(new java.awt.Color(187, 187, 100));
        panelCampos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("ID");
        panelCampos.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 20));

        jLabel1.setText("Region");
        panelCampos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, 50, 20));

        jLabel2.setText("Nombre");
        panelCampos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 112, 70, 20));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        panelCampos.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 180, -1));

        jLabel3.setText("Ap. Paterno");
        panelCampos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 70, 20));

        txtPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaternoActionPerformed(evt);
            }
        });
        panelCampos.add(txtPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 180, -1));

        jLabel4.setText("Ap. Materno");
        panelCampos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 192, 70, 20));

        txtMaterno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMaternoFocusLost(evt);
            }
        });
        txtMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaternoActionPerformed(evt);
            }
        });
        panelCampos.add(txtMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 180, -1));

        jLabel7.setText("Rut");
        panelCampos.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 72, 60, 20));

        txtRut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRut2ActionPerformed(evt);
            }
        });
        txtRut2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRut2KeyTyped(evt);
            }
        });
        panelCampos.add(txtRut2, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 70, 30, -1));
        panelCampos.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 40, 20));

        cbxRegion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxRegion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxRegionItemStateChanged(evt);
            }
        });
        cbxRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxRegionActionPerformed(evt);
            }
        });
        panelCampos.add(cbxRegion, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, 180, -1));

        cbxCiudad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxCiudad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCiudadItemStateChanged(evt);
            }
        });
        panelCampos.add(cbxCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, 180, -1));

        cbxSucursal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxSucursal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxSucursalItemStateChanged(evt);
            }
        });
        cbxSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSucursalActionPerformed(evt);
            }
        });
        panelCampos.add(cbxSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 180, -1));

        jLabel8.setText("Comuna");
        panelCampos.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 50, 20));

        jLabel9.setText("Ciudad");
        panelCampos.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 50, 20));

        jLabel5.setText("Direccion");
        panelCampos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 70, 20));

        jLabel10.setText("Telefono");
        panelCampos.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 70, 20));

        txtTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelActionPerformed(evt);
            }
        });
        txtTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelKeyTyped(evt);
            }
        });
        panelCampos.add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 180, -1));

        txtDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirActionPerformed(evt);
            }
        });
        txtDir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDirKeyTyped(evt);
            }
        });
        panelCampos.add(txtDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 180, -1));

        jLabel11.setText("Sucursal");
        panelCampos.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 70, 20));

        cbxComuna.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxComuna.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxComunaItemStateChanged(evt);
            }
        });
        cbxComuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxComunaActionPerformed(evt);
            }
        });
        panelCampos.add(cbxComuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, 180, -1));

        txtRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutActionPerformed(evt);
            }
        });
        txtRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRutKeyTyped(evt);
            }
        });
        panelCampos.add(txtRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 130, -1));

        jLabel12.setText("-");
        panelCampos.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 74, 10, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/folder/Fondo.jpg"))); // NOI18N
        panelCampos.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 230));

        PanelContenedor.add(panelCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 970, 230));

        panelTabla.setLayout(new java.awt.BorderLayout());

        TBVendedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11"
            }
        ));
        TBVendedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBVendedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBVendedor);

        panelTabla.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        PanelContenedor.add(panelTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 1010, 180));

        panelSuperiorBotones.setMaximumSize(new java.awt.Dimension(780, 45));
        panelSuperiorBotones.setMinimumSize(new java.awt.Dimension(780, 45));
        panelSuperiorBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setText("Agregar");
        btnAgregar.setMaximumSize(new java.awt.Dimension(200, 23));
        btnAgregar.setMinimumSize(new java.awt.Dimension(200, 23));
        btnAgregar.setPreferredSize(new java.awt.Dimension(200, 23));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        panelSuperiorBotones.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 5, -1, -1));

        btnModificar.setText("Modificar");
        btnModificar.setMaximumSize(new java.awt.Dimension(200, 23));
        btnModificar.setMinimumSize(new java.awt.Dimension(200, 23));
        btnModificar.setPreferredSize(new java.awt.Dimension(200, 23));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        panelSuperiorBotones.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 5, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.setMaximumSize(new java.awt.Dimension(200, 23));
        btnEliminar.setMinimumSize(new java.awt.Dimension(200, 23));
        btnEliminar.setPreferredSize(new java.awt.Dimension(200, 23));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        panelSuperiorBotones.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 5, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/folder/Fondo.jpg"))); // NOI18N
        panelSuperiorBotones.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 30));

        jLabel16.setText("jLabel16");
        panelSuperiorBotones.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, -1, -1));

        PanelContenedor.add(panelSuperiorBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 1030, 30));

        panelInferiorBotones.setMaximumSize(new java.awt.Dimension(780, 45));
        panelInferiorBotones.setMinimumSize(new java.awt.Dimension(780, 45));
        panelInferiorBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardar.setText("Guardar");
        btnGuardar.setMaximumSize(new java.awt.Dimension(200, 23));
        btnGuardar.setMinimumSize(new java.awt.Dimension(200, 23));
        btnGuardar.setPreferredSize(new java.awt.Dimension(200, 23));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panelInferiorBotones.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.setMaximumSize(new java.awt.Dimension(200, 23));
        btnLimpiar.setMinimumSize(new java.awt.Dimension(200, 23));
        btnLimpiar.setPreferredSize(new java.awt.Dimension(200, 23));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        panelInferiorBotones.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/folder/Fondo.jpg"))); // NOI18N
        panelInferiorBotones.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 40));

        PanelContenedor.add(panelInferiorBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 660, 460, 40));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("VENDEDOR");
        lblTitulo.setMaximumSize(new java.awt.Dimension(780, 44));
        lblTitulo.setMinimumSize(new java.awt.Dimension(780, 44));
        lblTitulo.setPreferredSize(new java.awt.Dimension(780, 44));
        PanelContenedor.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1050, 60));

        panelFiltrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxItemBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "id_vendedor","Nombre" }));
        jComboBoxItemBusqueda.setMaximumSize(new java.awt.Dimension(200, 23));
        jComboBoxItemBusqueda.setMinimumSize(new java.awt.Dimension(200, 23));
        jComboBoxItemBusqueda.setPreferredSize(new java.awt.Dimension(200, 23));
        jComboBoxItemBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxItemBusquedaActionPerformed(evt);
            }
        });
        panelFiltrar.add(jComboBoxItemBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 5, -1, -1));

        txtBusqueda.setMaximumSize(new java.awt.Dimension(200, 23));
        txtBusqueda.setMinimumSize(new java.awt.Dimension(200, 23));
        txtBusqueda.setPreferredSize(new java.awt.Dimension(200, 23));
        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyTyped(evt);
            }
        });
        panelFiltrar.add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 5, -1, -1));

        btnFiltrar.setText("Filtrar");
        btnFiltrar.setMaximumSize(new java.awt.Dimension(100, 23));
        btnFiltrar.setMinimumSize(new java.awt.Dimension(100, 23));
        btnFiltrar.setPreferredSize(new java.awt.Dimension(100, 23));
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });
        panelFiltrar.add(btnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 5, -1, -1));

        btnQuitarFiltro.setText("Quitar filtro");
        btnQuitarFiltro.setMaximumSize(new java.awt.Dimension(100, 23));
        btnQuitarFiltro.setMinimumSize(new java.awt.Dimension(100, 23));
        btnQuitarFiltro.setPreferredSize(new java.awt.Dimension(100, 23));
        btnQuitarFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarFiltroActionPerformed(evt);
            }
        });
        panelFiltrar.add(btnQuitarFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 5, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/folder/Fondo.jpg"))); // NOI18N
        panelFiltrar.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 40));

        PanelContenedor.add(panelFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 860, 40));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/folder/Fondo.jpg"))); // NOI18N
        PanelContenedor.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1060, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 1023, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContenedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtRut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRut2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRut2ActionPerformed

    private void TBVendedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBVendedorMouseClicked
        //Al seleccionar item de la tabla, se actualizan campos y se activa botón Modificar
        if(btnAgregar.isSelected()){
            btnAgregar.setSelected(false);
            btnAgregar.setBackground(null);
            btnModificar.setSelected(true);
            btnModificar.setBackground(Color.GRAY);
        }
//        comprobarCampos();
        obtenerCampos();
    }//GEN-LAST:event_TBVendedorMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Limpiar.contenidoPanel(panelCampos);
        btnAgregar.setSelected(true);
        btnAgregar.setBackground(Color.GRAY);
        btnModificar.setSelected(false);
        btnModificar.setBackground(null);
     
        Connection conn;
        Statement st;
        ResultSet rs;
        
            
        try {
            conn = BDConexion.getConexion();
            st = conn.createStatement();
            rs = st.executeQuery("SELECT * FROM vendedor ORDER by id_vendedor desc LIMIT 1");
            while(rs.next()){
                
                int p=Integer.parseInt(rs.getString("id_vendedor"))+1;
                txtID.setText(Integer.toString(p));
                txtID.disable();
                
            }
        } catch (Exception e) {
        }
       
        
        panelCampos.setVisible(true);
        panelInferiorBotones.setVisible(true);
        txtRut.enable();
        txtRut.requestFocus();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        //Se activa selección de botón Modificar y de desactiva botón Agregar
        btnModificar.setSelected(true);
        btnModificar.setBackground(Color.GRAY);
        btnAgregar.setSelected(false);
        btnAgregar.setBackground(null);

        //Se obtienen datos de fila seleccionada en la tabla y se cargan los campos correspondientes
        obtenerCampos();

//        comprobarCampos();
        panelCampos.setVisible(true);
        panelInferiorBotones.setVisible(true);
        txtNombre.requestFocus();

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       //este boton manda un mensaje de alerta que dira si realmente se desea eliminar 
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Esta seguro?", "Alerta!", JOptionPane.YES_NO_OPTION);
        if ( respuesta == 0){
            //Se obtiene ID para eliminar registro
            int rowSel = TBVendedor.getSelectedRow();
            int reg = (Integer) TBVendedor.getValueAt(rowSel, 0);
            BDVendedor.eliminar(reg);
            BDVendedor.listar(TBVendedor);
            Limpiar.contenidoPanel(panelCampos);
            txtID.setText("");
        }
//        comprobarCampos();
    }//GEN-LAST:event_btnEliminarActionPerformed
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        //Se agrega o modifica registro según botón seleccionado.
        try{
            
            String id = txtID.getText();
            
            String rut = txtRut.getText()+"-"+txtRut2.getText();
            String nom = txtNombre.getText();
            String pat = txtPaterno.getText();
            String mat = txtMaterno.getText();
            String dir = txtDir.getText();
            String tel = txtTel.getText();
            
            Comuna loc = (Comuna) cbxComuna.getSelectedItem();
            Sucursal s = (Sucursal) cbxSucursal.getSelectedItem();
            String com=Integer.toString(loc.getId());
            String suc = Integer.toString(s.getId_sucursal());
            if(btnAgregar.isSelected()){
                
                BDVendedor.insertar(rut,nom,pat,mat,dir,tel,com,suc);
                BDVendedor.listar(TBVendedor);
                Limpiar.contenidoPanel(panelCampos);
//                comprobarCampos();
            }else if(btnModificar.isSelected()){
                int idf = Integer.parseInt(id);
              BDVendedor.modificar(id,rut,nom,pat,mat,dir,tel,com,suc);
                BDVendedor.listar(TBVendedor);
                Limpiar.contenidoPanel(panelCampos);
//                comprobarCampos();
            }
        }catch(Exception e){
            System.err.println("Excepción al guardar : " + e);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        //Se limpias campos
        Limpiar.contenidoPanel(panelCampos);
//        comprobarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jComboBoxItemBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxItemBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxItemBusquedaActionPerformed

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
        btnFiltrar.requestFocus();
    }//GEN-LAST:event_txtBusquedaActionPerformed

    private void txtBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyTyped
            
    }//GEN-LAST:event_txtBusquedaKeyTyped
 
    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        String criterioBusqueda = jComboBoxItemBusqueda.getSelectedItem().toString();
        String textoBusqueda = txtBusqueda.getText();
        System.out.println("Campo a buscar: " + criterioBusqueda);
        System.out.println("Criterio a buscar: " + criterioBusqueda);

        if (criterioBusqueda.equals("id_vendedor")){
            BDVendedor.filtrar(TBVendedor, "id_vendedor", textoBusqueda);
        }else if (criterioBusqueda.equals("Nombre")){
            BDVendedor.filtrar(TBVendedor, "nombre", textoBusqueda);
        }
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void btnQuitarFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarFiltroActionPerformed
        txtBusqueda.setText("");
        BDVendedor.listar(TBVendedor);
//        comprobarCampos();
    }//GEN-LAST:event_btnQuitarFiltroActionPerformed

    private void txtRut2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRut2KeyTyped
        // TODO add your handling code here:
        if (txtRut2.getText().length()>=1) {
            evt.consume();
            
        }
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_txtRut2KeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        

    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtMaternoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaternoFocusLost
        
    }//GEN-LAST:event_txtMaternoFocusLost

    private void txtPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaternoActionPerformed

    private void txtMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaternoActionPerformed

    private void cbxRegionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxRegionItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            Region est = (Region) cbxRegion.getSelectedItem();
            Ciudad mun = new Ciudad();
            DefaultComboBoxModel modelMunicipio = new DefaultComboBoxModel(mun.mostrarCiudad(est.getId()));
            cbxCiudad.setModel(modelMunicipio);
            cbxComuna.removeAllItems();
           
        }
    }//GEN-LAST:event_cbxRegionItemStateChanged

    private void cbxCiudadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCiudadItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            Ciudad mun = (Ciudad) cbxCiudad.getSelectedItem();
            Comuna loc = new Comuna();
            DefaultComboBoxModel modelLocalidad = new DefaultComboBoxModel(loc.mostrarComuna(mun.getId()));
            modelLocalidad.removeElementAt(0);
            cbxComuna.setModel(modelLocalidad);
        }
    }//GEN-LAST:event_cbxCiudadItemStateChanged

    private void cbxSucursalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxSucursalItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            
        }
    }//GEN-LAST:event_cbxSucursalItemStateChanged

    private void cbxSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSucursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSucursalActionPerformed

    private void cbxRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRegionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxRegionActionPerformed

    private void txtTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelActionPerformed

    private void txtDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirActionPerformed

    private void txtDirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDirKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirKeyTyped

    private void cbxComunaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxComunaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxComunaItemStateChanged

    private void cbxComunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxComunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxComunaActionPerformed

    private void txtTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
        if (txtTel.getText().length()>=9) {
            evt.consume();
            
        }
    }//GEN-LAST:event_txtTelKeyTyped

    private void txtRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutActionPerformed
        
    }//GEN-LAST:event_txtRutActionPerformed

    private void txtRutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutKeyTyped
        if (txtRut.getText().length()>=8) {
            evt.consume();
            
        }
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
        
    }//GEN-LAST:event_txtRutKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazVendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContenedor;
    private javax.swing.JTable TBVendedor;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnQuitarFiltro;
    private javax.swing.JComboBox<String> cbxCiudad;
    private javax.swing.JComboBox<String> cbxComuna;
    private javax.swing.JComboBox<String> cbxRegion;
    private javax.swing.JComboBox<String> cbxSucursal;
    private javax.swing.JComboBox<String> jComboBoxItemBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelCampos;
    private javax.swing.JPanel panelFiltrar;
    private javax.swing.JPanel panelInferiorBotones;
    private javax.swing.JPanel panelSuperiorBotones;
    private javax.swing.JPanel panelTabla;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtDir;
    private javax.swing.JLabel txtID;
    private javax.swing.JTextField txtMaterno;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPaterno;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtRut2;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables

    private boolean validaDatosServ() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
}
