/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Conexion.BDConexion;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author tridente
 */
public class InterfazServicio extends javax.swing.JFrame {

    /**
     * Creates new form InterfazServicio
     */
    public InterfazServicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEdi = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnRegServ = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtDes = new javax.swing.JTextField();
        txtDur = new javax.swing.JTextField();
        txtPre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnFil = new javax.swing.JButton();
        txtFil = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEdi.setText("Editar");
        getContentPane().add(btnEdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 313, -1, -1));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Tipo", "Descripcion", "Duracion", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 167, -1, 91));

        jLabel8.setText("Precio");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 267, -1, -1));

        jLabel9.setText("Tipo de servicio");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 150, -1, -1));

        jLabel11.setText("Descripcion");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 190, -1, -1));

        jLabel12.setText("Duracion");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 230, -1, -1));

        btnRegServ.setText("Registrar");
        btnRegServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegServActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 313, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 147, -1, -1));

        txtDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDesActionPerformed(evt);
            }
        });
        txtDes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDesKeyTyped(evt);
            }
        });
        getContentPane().add(txtDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 187, 56, -1));

        txtDur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDurKeyTyped(evt);
            }
        });
        getContentPane().add(txtDur, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 227, 56, -1));

        txtPre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPreKeyTyped(evt);
            }
        });
        getContentPane().add(txtPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 264, 56, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Servicio");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 23, -1, -1));

        btnFil.setText("Filtrar");
        btnFil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilActionPerformed(evt);
            }
        });
        getContentPane().add(btnFil, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 128, -1, -1));
        getContentPane().add(txtFil, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 129, 87, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/folder/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegServActionPerformed
        Connection conn = BDConexion.getConexion();
        if (conn != null){
            if(!validaDatosServ()){
                JOptionPane.showMessageDialog(this,"Ingrese datos faltantes.","No hay datos",3);
            }
        }
    }//GEN-LAST:event_btnRegServActionPerformed

    private void btnFilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnFilActionPerformed

    private void txtDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDesActionPerformed

    private void txtDesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDesKeyTyped
        // TODO add your handling code here:
        char c; 
        c = evt.getKeyChar ();
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' '||c>' ')) evt.consume();
    }//GEN-LAST:event_txtDesKeyTyped

    private void txtDurKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDurKeyTyped
        // TODO add your handling code here:
        char c; 
        c = evt.getKeyChar ();
        if((c<'0' || c>'9')) evt.consume();
    }//GEN-LAST:event_txtDurKeyTyped

    private void txtPreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPreKeyTyped
        // TODO add your handling code here:
        char c; 
        c = evt.getKeyChar ();
        if((c<'0' || c>'9')) evt.consume();
    }//GEN-LAST:event_txtPreKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazServicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdi;
    private javax.swing.JButton btnFil;
    private javax.swing.JButton btnRegServ;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField txtDes;
    private javax.swing.JTextField txtDur;
    private javax.swing.JTextField txtFil;
    private javax.swing.JTextField txtPre;
    // End of variables declaration//GEN-END:variables

    private boolean validaDatosServ() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
